# Generated by Django 5.2.8 on 2025-12-04 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('correo', models.EmailField(blank=True, max_length=255)),
                ('nombre', models.CharField(max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono_alternativo', models.CharField(blank=True, max_length=20, null=True)),
                ('ultima_modificacion_username', models.DateTimeField(blank=True, null=True)),
                ('calle', models.CharField(blank=True, max_length=500, null=True)),
                ('colonia', models.CharField(blank=True, max_length=200, null=True)),
                ('codigo_postal', models.CharField(blank=True, max_length=5, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=200, null=True)),
                ('estado', models.CharField(blank=True, max_length=100, null=True)),
                ('referencias', models.TextField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=500, null=True)),
                ('tipo_cliente', models.CharField(choices=[('menudeo', 'Menudeo'), ('mayoreo', 'Mayoreo')], default='menudeo', max_length=20)),
                ('rfc', models.CharField(blank=True, max_length=13, null=True)),
                ('razon_social', models.CharField(blank=True, max_length=500, null=True)),
                ('direccion_fiscal', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlacklistedToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ContactoCliente',
            fields=[
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nombre', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('mensaje', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40, null=True)),
                ('status', models.CharField(default='vacio', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carritos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=50)),
                ('payment_method', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('carrito', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.carrito')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('genero', models.CharField(max_length=50)),
                ('precio_mayorista', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('en_oferta', models.BooleanField(default=False)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Variante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, help_text='Código interno o UPC (ej: NIKE-AIR-38-BLK)', max_length=100, null=True)),
                ('talla', models.CharField(db_index=True, default='UNICA', help_text='Talla del producto (ej: 38, M, L, UNICA, N/A)', max_length=20)),
                ('color', models.CharField(db_index=True, default='N/A', help_text='Color principal del producto', max_length=50)),
                ('otros', models.JSONField(blank=True, default=dict, help_text='Atributos extras en JSON: material, dimensiones, peso, etc.')),
                ('precio', models.DecimalField(blank=True, decimal_places=2, help_text='Precio específico de esta variante (si difiere del producto base)', max_digits=10, null=True)),
                ('precio_mayorista', models.DecimalField(decimal_places=2, default=0, help_text='Precio para clientes mayoristas', max_digits=10)),
                ('stock', models.IntegerField(db_index=True, default=0, help_text='Cantidad disponible en inventario')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='store.producto')),
            ],
            options={
                'ordering': ['talla', 'color'],
            },
        ),
        migrations.CreateModel(
            name='OrdenDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='store.orden')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.variante')),
            ],
        ),
        migrations.CreateModel(
            name='CarritoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.carrito')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.variante')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('productos', models.ManyToManyField(blank=True, related_name='wishlists', to='store.producto')),
            ],
        ),
        migrations.AddIndex(
            model_name='variante',
            index=models.Index(fields=['talla', 'color', 'stock'], name='store_varia_talla_a46dc4_idx'),
        ),
        migrations.AddIndex(
            model_name='variante',
            index=models.Index(fields=['producto', 'stock'], name='store_varia_product_e66c22_idx'),
        ),
    ]
