# Generated by Django 4.2.25 on 2025-12-10 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='categorias/'),
        ),
        migrations.AddField(
            model_name='variante',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen específica de esta variante (ej: talla 38 en color negro)', null=True, upload_to='variantes/'),
        ),
        migrations.CreateModel(
            name='ProductoImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='productos/galeria/')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de aparición en el carrusel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='store.producto')),
            ],
            options={
                'verbose_name': 'Imagen de Producto',
                'verbose_name_plural': 'Imágenes de Productos',
                'ordering': ['orden', 'created_at'],
            },
        ),
    ]
