# Generated by Django 4.2.25 on 2026-01-05 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_categoria_imagen_variante_imagen_productoimagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.CharField(blank=True, db_index=True, help_text='Marca del producto para filtros', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='genero',
            field=models.CharField(blank=True, help_text='[DEPRECATED] Usar subcategoria. Mantener por compatibilidad.', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='subcategorias/')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de aparición en filtros')),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='store.categoria')),
            ],
            options={
                'verbose_name': 'Subcategoría',
                'verbose_name_plural': 'Subcategorías',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='subcategoria',
            field=models.ForeignKey(blank=True, help_text='Subcategoría para filtros avanzados (género, marca, promoción, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='store.subcategoria'),
        ),
        migrations.AddIndex(
            model_name='subcategoria',
            index=models.Index(fields=['categoria', 'activa'], name='store_subca_categor_45cffe_idx'),
        ),
        migrations.AddIndex(
            model_name='subcategoria',
            index=models.Index(fields=['nombre'], name='store_subca_nombre_928ac1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subcategoria',
            unique_together={('categoria', 'nombre')},
        ),
    ]
