# Generated by Django 4.2.25 on 2026-01-05 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_producto_marca_alter_producto_genero_subcategoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VarianteImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(help_text='Imagen de la variante desde diferentes ángulos', upload_to='variantes/galeria/')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de aparición en el carrusel (1-5)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Imagen de Variante',
                'verbose_name_plural': 'Imágenes de Variantes',
                'ordering': ['orden', 'created_at'],
            },
        ),
        migrations.AlterField(
            model_name='productoimagen',
            name='orden',
            field=models.PositiveIntegerField(default=0, help_text='Orden de aparición en el carrusel (1-5)'),
        ),
        migrations.AddConstraint(
            model_name='productoimagen',
            constraint=models.UniqueConstraint(fields=('producto', 'orden'), name='unique_producto_imagen_orden'),
        ),
        migrations.AddField(
            model_name='varianteimagen',
            name='variante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_carrusel', to='store.variante'),
        ),
        migrations.AddConstraint(
            model_name='varianteimagen',
            constraint=models.UniqueConstraint(fields=('variante', 'orden'), name='unique_variante_imagen_orden'),
        ),
    ]
