# Generated by Django 4.2.25 on 2026-01-05 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_varianteimagen_alter_productoimagen_orden_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='subcategoria',
        ),
        migrations.AddField(
            model_name='producto',
            name='subcategorias',
            field=models.ManyToManyField(blank=True, help_text='Múltiples subcategorías (marca, oferta, línea, etc.)', related_name='productos', to='store.subcategoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='genero',
            field=models.CharField(blank=True, db_index=True, help_text='Hombre, Mujer, Ambos, etc.', max_length=50, null=True),
        ),
    ]
