# Generated by Django 5.2.8 on 2026-01-05 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variante_imagen'),
        ('store', '0005_remove_producto_subcategoria_producto_subcategorias_and_more'),
    ]

    operations = [
    ]
