# Generated by Django 5.2.8 on 2026-01-06 01:40

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_merge_20260105_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
        migrations.AlterField(
            model_name='productoimagen',
            name='imagen',
            field=models.ImageField(upload_to=store.models.producto_imagen_upload_to),
        ),
        migrations.AlterField(
            model_name='variante',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen específica de esta variante (color/talla específica)', null=True, upload_to='variantes/'),
        ),
        migrations.AlterField(
            model_name='varianteimagen',
            name='imagen',
            field=models.ImageField(help_text='Imagen de la variante desde diferentes ángulos', upload_to=store.models.variante_imagen_upload_to),
        ),
    ]
