# Generated by Django 5.2.8 on 2026-01-06 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_producto_imagen_alter_productoimagen_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='varianteimagen',
            name='variante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='store.variante'),
        ),
    ]
