# Generated by Django 4.2.25 on 2026-01-07 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_varianteimagen_variante'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='email_verification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='email_verification_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
