# Generated by Django 4.2.25 on 2025-11-27 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_cliente_calle_cliente_ciudad_cliente_codigo_postal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ultima_modificacion_username',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
