# Generated by Django 5.2.8 on 2026-01-08 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_add_email_verification_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='conekta_charge_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='conekta_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
