# Generated by Django 4.2.25 on 2026-01-18 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_orden_conekta_charge_id_orden_conekta_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='carrito',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.carrito'),
        ),
    ]
