# Generated by Django 5.2.8 on 2026-02-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_convert_genero_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='variante',
            name='es_variante_principal',
            field=models.BooleanField(db_index=True, default=False, help_text='Indica si es la variante principal del producto (para mostrar imágenes por defecto)'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='genero',
            field=models.CharField(blank=True, choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer'), ('Unisex', 'Unisex')], db_index=True, help_text='Género del producto', max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='ProductoImagen',
        ),
    ]
