# Generated by Django 5.2.8 on 2026-02-24 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_variante_tallas_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='stock_reducido',
            field=models.BooleanField(default=False, help_text='Indica si ya se redujo el stock del inventario'),
        ),
    ]
