# Generated by Django 5.2.8 on 2026-02-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_orden_stock_reducido'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='bodega',
            field=models.BooleanField(db_index=True, default=True, help_text='Si es True, el producto NO se muestra en la vista pública (solo visible desde inventario/dashboard)'),
        ),
    ]
