@token_admin= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJyb2xlIjoiYWRtaW4iLCJ0eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcwMzM2OTgzLCJpYXQiOjE3NzAzMzUxODMsInVzZXJuYW1lIjoiYWRtaW4ifQ.3cTRS9TnvQROZ_g3lWQbB_wSdjHtr3FFJN11rTQjAtY
POST http://127.0.0.1:8000/auth/login_user/
Content-Type: application/json

{
  "username": "admin",
  "password": "admin123"
}


### LOGIN CLIENTE
POST http://127.0.0.1:8000/auth/login_client/
Content-Type: application/json

{
  "username": "jona.emir@hotmail.com",
  "password": "123456"
}

###
POST http://127.0.0.1:8000/api/categorias/crear/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3NTU5ODg0NTcsImlhdCI6MTc1NTk4MTI1N30.f4uxrGiFfFjBt8taUjCiOIctPPPq7pVDwRK-khSen6w

{
  "nombre": "Caballero"
}


###
POST http://127.0.0.1:8000/clientes/crear/
Content-Type: application/json

{
  "username": "cliente1",
  "password": "mipassword",
  "correo":   "cliente1@example.com",
  "nombre":   "Cliente Uno"
}


### obtener productos
GET http://127.0.0.1:8000/api/productos/ 

###
DELETE http://127.0.0.1:8000/api/productos/delete/all/
### Crear productos
POST http://127.0.0.1:8000/api/productos/crear/
Content-Type: application/json

{
  "nombre": "Forumm",
  "descripcion": "Tenis para correr",
  "precio": 119.99,
  "categoria_id": 1,
  "genero": "Unisex",
  "en_oferta": false,
  "imagen": "newBalance.jpg",
  "stock": 35
}

###
POST http://127.0.0.1:8000/api/productos/update/3/
Content-Type: application/x-www-form-urlencoded

nombre=AirForce&stock=30

### DELETE
DELETE http://127.0.0.1:8000/api/productos/delete/2/

### GET clientes
GET http://127.0.0.1:8000/user/get/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3NTY2Mjg2OTcsImlhdCI6MTc1NjYyMTQ5N30.yXxecQtsaQNd3hZSs1rqmBhwmdJgfTQTzYGqA7Moh6k

### GET clientes
GET http://127.0.0.1:8000/clientes/
Authorization: Bearer {{token_admin}}

### Crear cliente

POST http://127.0.0.1:8000/user/create/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3NTY2Mjg2OTcsImlhdCI6MTc1NjYyMTQ5N30.yXxecQtsaQNd3hZSs1rqmBhwmdJgfTQTzYGqA7Moh6k

{
  "username": "admin2",
  "password": "admin2123",
  "role":   "admin"
}

###
DELETE http://127.0.0.1:8000/clientes/delete/4/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3NTY2Mjg2OTcsImlhdCI6MTc1NjYyMTQ5N30.yXxecQtsaQNd3hZSs1rqmBhwmdJgfTQTzYGqA7Moh6k




### Actualizar cliente
POST http://127.0.0.1:8000/clientes/update/1/
Content-Type: application/json

{
  "nombre": "Angel"
}

###

POST http://127.0.0.1:8000/user/create/
Content-Type: application/json

{
  "username": "jona",
  "password": "123456",
  "role": "cliente"
}




### Crear contacto

POST http://127.0.0.1:8000/contact/create/1
Content-Type: application/json

{
  "nombre": "Angel Adrian",
  "email": "adrian@gmail.com",
  "mensaje": "Hola hoña"
}


###
POST http://127.0.0.1:8000/contact/update/1
Content-Type: application/json

{
  "email": "adrian@gmail.com"
}

###
GET http://127.0.0.1:8000/user/

###
POST http://127.0.0.1:8000/user/create
Content-Type: application/json

{
  "username": "admin",
  "password": "123456",
  "role": "Admin"
}




### Crear un carrito para el cliente #5
POST http://127.0.0.1:8000/api/carrito/create/16/ HTTP/1.1
Content-Type: application/json

{
  "status": "activo"
}

###

### Actualizar solo el status del carrito #7 (PATCH)
PATCH http://127.0.0.1:8000/api/carrito/7/ HTTP/1.1
Content-Type: application/json

{
  "status": "procesando"
}

###

### Actualizar cliente y status del carrito #7 (PUT)
PUT http://127.0.0.1:8000/api/carrito/7/ HTTP/1.1
Content-Type: application/json

{
  "cliente_id": 3,
  "status":     "pagado"
}


###
GET http://127.0.0.1:8000/wishlist/1/
###

###
PATCH http://127.0.0.1:8000/wishlist/1/
Content-Type: application/json

{
  "producto_id": 3
}

###
DELETE http://127.0.0.1:8000/wishlist/all/1/

###
POST http://127.0.0.1:8000/api/categorias/crear/ HTTP/1.1
Content-Type: application/json

{
  "nombre": "Dama"
}

###
GET http://127.0.0.1:8000/api/categorias

### Obtener carrito activo del cliente 1
GET http://127.0.0.1:8000/api/carrito/1/ HTTP/1.1
Accept: application/json

### Agregar producto al carrito del cliente 1
POST http://127.0.0.1:8000/api/carrito/create/16/ HTTP/1.1
Content-Type: application/json

{
  "producto_id": 22,
  "talla": "25",
  "cantidad": 1
}



### Vaciar carritp
### Vaciar todo el carrito del cliente 1
DELETE http://127.0.0.1:8000/api/carrito/1/empty/ HTTP/1.1
Accept: application/json

### Eliminar la variante (producto) con ID 5 del carrito del cliente 1 hacer get products para verificar el id de la variante
DELETE http://127.0.0.1:8000/api/carrito/1/item/5/ HTTP/1.1
Accept: application/json

###
POST http://127.0.0.1:8000/ordenar/1/enviar/


###
GET http://127.0.0.1:8000/orden/3/


###
POST http://127.0.0.1:8000/orden/procesando/1/


###
DELETE http://127.0.0.1:8000/orden/delete/2/

###

DELETE http://127.0.0.1:8000/orden/delete/3/111
