"""
Django settings for ecommerce project.

Generated by 'django-admin startproject' using Django 5.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from decouple import config


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'SECRET_KEY'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Google Maps API Key (obtener en https://console.cloud.google.com/)
GOOGLE_MAPS_API_KEY = config('GOOGLE_MAPS_API_KEY', default='')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',  # Para permitir peticiones desde el frontend
    'storages',     # AWS S3 integration
    'store',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # Debe estar antes de CommonMiddleware
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ecommerce.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',  # Para variable 'debug' en templates
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ecommerce.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Configuración para PostgreSQL con Docker
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME', default='nowhere_db'),
        'USER': config('DB_USER', default='postgres'),
        'PASSWORD': config('DB_PASSWORD', default='postgres123'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5432'),
        'OPTIONS': {
            'client_encoding': 'UTF8',
        },
    }
}

# Para volver a SQLite (desarrollo individual), comenta lo anterior y descomenta:
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",  # <-- aquí estás apuntando a tu carpeta static/
]


# ───────── Configuración de AWS S3 ──────────
USE_S3 = config('USE_S3', default='False') == 'True'

if USE_S3:
    # AWS Credentials
    AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = config('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_REGION_NAME = config('AWS_S3_REGION_NAME', default='us-east-1')
    
    # S3 Settings
    AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'
    AWS_S3_OBJECT_PARAMETERS = {
        'CacheControl': 'max-age=86400',  # 1 día de cache
    }
    AWS_DEFAULT_ACL = None  # Bucket usa políticas, no ACLs
    AWS_S3_FILE_OVERWRITE = False
    AWS_QUERYSTRING_AUTH = False  # No agregar parámetros de autenticación a las URLs
    AWS_LOCATION = 'media'  # Carpeta base en S3
    
    # Django 5.2+ Storage configuration (STORAGES dict)
    STORAGES = {
        'default': {
            'BACKEND': 'storages.backends.s3boto3.S3Boto3Storage',
            'OPTIONS': {
                'bucket_name': AWS_STORAGE_BUCKET_NAME,
                'region_name': AWS_S3_REGION_NAME,
                'access_key': AWS_ACCESS_KEY_ID,
                'secret_key': AWS_SECRET_ACCESS_KEY,
                'location': AWS_LOCATION,
                'custom_domain': AWS_S3_CUSTOM_DOMAIN,
                'file_overwrite': AWS_S3_FILE_OVERWRITE,
                'default_acl': AWS_DEFAULT_ACL,
                'querystring_auth': AWS_QUERYSTRING_AUTH,
                'object_parameters': AWS_S3_OBJECT_PARAMETERS,
            }
        },
        'staticfiles': {
            'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
        }
    }
    
    # Media files location
    MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/{AWS_LOCATION}/'
    MEDIA_ROOT = ''  # No se usa con S3
else:
    # Local storage (desarrollo)
    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
    
    # Django 5.2+ Storage configuration (STORAGES dict)
    STORAGES = {
        'default': {
            'BACKEND': 'django.core.files.storage.FileSystemStorage',
        },
        'staticfiles': {
            'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
        }
    }

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ───────── Seguridad de sesión y cookies ──────────
SESSION_COOKIE_SECURE       = False   # ⚠️ Activa (True) solo en producción con HTTPS
CSRF_COOKIE_SECURE          = False   # ⚠️ Activa (True) solo en producción con HTTPS
SESSION_COOKIE_HTTPONLY     = True    # Protege contra JS, mantenlo activo
CSRF_COOKIE_HTTPONLY        = True    # Protege contra JS, mantenlo activo
SESSION_COOKIE_SAMESITE     = "Lax"   # Puedes dejarlo así en local
CSRF_COOKIE_SAMESITE        = "Lax"

# ───────── Cabeceras hardening ──────────
SECURE_BROWSER_XSS_FILTER   = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS             = "DENY"

# ───────── Redirección forzada a HTTPS ──────────
SECURE_SSL_REDIRECT         = False  # ⚠️ Activa (True) en producción con HTTPS

# ───────── HSTS (HTTP Strict Transport Security) ──────────
SECURE_HSTS_SECONDS             = 0      # ⚠️ Sube a 31536000 en producción
SECURE_HSTS_INCLUDE_SUBDOMAINS = False  # ⚠️ True en producción
SECURE_HSTS_PRELOAD            = False  # ⚠️ True en producción

# ───────── Tiempo de sesión ──────────
SESSION_COOKIE_AGE = 60 * 60 * 2   # 2 h de inactividad

# ───────── Producción: desactivar DEBUG y definir hosts ──────────
DEBUG = True                      # ⚠️ Cambia a False en producción
ALLOWED_HOSTS = ['*']

# ⚠️ Cuando tengas HTTPS y dominio personalizado, reemplaza por:
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True
# SECURE_SSL_REDIRECT = True
# SECURE_HSTS_SECONDS = 31536000
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_HSTS_PRELOAD = True
# DEBUG = False
# ALLOWED_HOSTS = ["nowhere.mx", "www.nowhere.mx"]
# CSRF_TRUSTED_ORIGINS = ["https://nowhere.mx"]  # Si usas frontend externo


# ───────── Configuración de correo ──────────
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
#Autenticacion para poder recuperar contrase;as
AUTH_USER_MODEL = 'store.Cliente'

# ───────── Configuración Twilio ──────────
TWILIO_ACCOUNT_SID    = config("TWILIO_ACCOUNT_SID")
TWILIO_AUTH_TOKEN     = config("TWILIO_AUTH_TOKEN")
TWILIO_WHATSAPP_FROM  = config("TWILIO_WHATSAPP_FROM")
TWILIO_ADMIN_PHONE    = config("TWILIO_ADMIN_PHONE")  # ← agrega esta variable al .env también


# ───────── Configuración JWT ──────────
JWT_SECRET_KEY = config('JWT_SECRET_KEY', default='tu-clave-secreta-muy-segura-cambiar-en-produccion')

# ───────── Configuración CORS ──────────
# Permitir peticiones desde el frontend
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",       # React
    "http://localhost:5173",       # Vite
    "http://127.0.0.1:3000",
    "http://127.0.0.1:5173",
    "http://localhost:8080",       # Otros frontends
]

# Headers permitidos para JWT
CORS_ALLOW_HEADERS = [
    'accept',
    'authorization',
    'content-type',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Permitir credenciales (cookies, headers de autorización)
CORS_ALLOW_CREDENTIALS = True





